intel/openvino-rs

crates/openvino/tests/classify-alexnet.rs, crates/openvino/tests/classify-inception.rs, crates/openvino/tests/classify-mobilenet.rs, crates/openvino/tests/util.rs
This change introduces a test utility, `util::Prediction`, that simplifies the classification tests. Using the `float-cmp` crate, it checks that the expected results have the correct ID and that the classification probability matches within a certain `DEFAULT_MARGIN` of error.
=> Allow classification results to deviate slightly

.github/workflows/main.yml, Cargo.lock, Dockerfile, crates/openvino-sys/build.rs, crates/openvino-tensor-converter/Cargo.toml
GitHub's `ubuntu-latest` runner uses Ubuntu 20.04 whereas previously it used Ubuntu 18.04. As a result, several dependencies must change
- libusb has a different name
- opencv uses the 4.x branch (previously 3.2)
=> Update runner dependencies

README.md
=> Update README.md to cover git-lfs

.github/workflows/main.yml, Cargo.toml, Dockerfile, README.md, crates/openvino-tensor-converter/Cargo.lock, crates/openvino-tensor-converter/Cargo.toml, crates/openvino/tests/classify-alexnet.rs, crates/openvino/tests/classify-inception.rs, crates/openvino/tests/classify-mobilenet.rs
This first disables the automatic building of `openvino-tensor-converter` as a part of the workspace: 1) it is likely not an intended target for the average user, and 2) the OpenCV dependencies are tricky to get right between OS versions (even within Linux). Then this creates a CI matrix for building the OpenVINO Rust bindings on different OS and OpenVINO versions. In order to account for extra validation done upstream in [SetBlob](https://github.com/openvinotoolkit/openvino/pull/2402/files#diff-0ec2c2a8d308ceb06e9f0d16319099aa1bb461c49a19e51c5267ced413f25f77R278-R280), this also includes a change to explicitly set the layout of the model input to use `NHWC`.
This change should confirm that openvino-rs works on OpenVINO versions 2020.4-2021.3, at least on Ubuntu. See #5 for extending …
=> Build different variants of OS and OpenVINO versions in CI

Cargo.lock, crates/openvino-sys/Cargo.toml, crates/openvino-sys/build.rs, crates/openvino/src/core.rs, crates/openvino/src/network.rs, crates/openvino/src/request.rs, crates/openvino/src/tensor_desc.rs
Previously, many libc types and functions were exported by openvino-sys (and visible in docs.rs). This change tightens up rust-bindgen to only emit the `ie_*` functions (and their recursively-used types, a default setting). It also eliminates some `__uint8_t` and `__int64_t` as well as properly transforming `size_t` to `usize`.
=> Only export the inference engine functions in openvino-sys 

crates/openvino-finder/README.md, crates/openvino/Cargo.toml, crates/openvino/src/core.rs, crates/openvino/src/error.rs, crates/openvino/src/lib.rs
While integrating with external libraries, the changes in this PR became apparent:
- I needed a way to turn on the `runtime-linking` feature when `openvino` was imported as a Cargo dependency
- and I needed a way to return errors instead of panicking when library loading fails.
=> More runtime-linking changes

.github/workflows/main.yml, .gitmodules, Cargo.lock, crates/openvino-finder/Cargo.toml, crates/openvino-finder/src/lib.rs
Also, provides sane defaults for unsupported target OS combinations to avoid build failures and fixes the `from-source` build failures.
=> openvino-finder: add logging, OPENVINO_BUILD_DIR

crates/openvino/src/error.rs, crates/openvino/src/network.rs, crates/openvino/tests/setup.rs
This change is an adaptation of #33 that allows for the same kind of functionality. It also adds tests checking the newly-added functions. With this in place, users will be able to set input layouts with something like:
```rust
for i in 0..network.get_inputs_len() {
let name = network.get_input_name(i)?;
network.set_input_layout(&name, Layout::NHWC)?;
}
```
=> Add `get_[inputs|outputs]_len` to `CNNNetwork`

.github/workflows/main.yml, Dockerfile, README.md, crates/openvino-finder/src/lib.rs, crates/openvino-sys/Cargo.toml, crates/openvino-sys/build.rs, crates/openvino-sys/src/generated/functions.rs, crates/openvino-sys/src/generated/types.rs, crates/openvino-sys/src/lib.rs, crates/openvino-sys/src/linking/runtime.rs, crates/xtask/src/codegen.rs
The 2022 release changes the names of several of the shared libraries
produced by OpenVINO as well as their directory structure. The C API is
still available, however, so this change continues to use that for the
time being instead of the newer v2.0 API.
Because of the significant changes to the release structure, there is a
decision to be made regarding backwards compatibility--e.g., using older
versions of OpenVINO with this binding crate. This change makes the
decision to stop supporting pre-2022 installations of OpenVINO in
ongoing versions of this crate: once this crate is released (`v0.4.0`),
users will have to decide whether to use this version for the newest
versions of OpenVINO or downgrade to a previously-released crate
(`v0.3.*`) for pre-2022 versions of OpenVINO.
=> Upgrade to use upstream OpenVINO 2022.1 release

.github/workflows/main.yml, Cargo.lock, README.md, crates/openvino-finder/src/lib.rs, crates/openvino-sys/Cargo.toml, crates/openvino-sys/build.rs
Prior to this change, the `openvino-sys` crate had the ability to build
OpenVINO from source using CMake from within its `build.rs` script. This
increased complexity in various places (documentation, `Cargo.toml`
features, `build.rs`) and was prone to breakage as OpenVINO modified its
available CMake build features.
Instead of providing a `from-source` feature to do all this, this change
documents an `OPENVINO_BUILD_DIR` environment variable that can be used
for the same purpose: once a user has built OpenVINO from source on
their system, they can provide the path to this repository for the
`openvino-sys` crate to bind to. The `openvino-finder` crate contains
the necessary paths to find the default locations of all of required
libraries.
=> Remove the `from-source` feature

Cargo.lock, crates/openvino-sys/Cargo.toml, crates/openvino-sys/src/linking/runtime.rs
The Rust ecosystem is generally migrating away from lazy_static to
once_cell, for example [in wasmtime].
This patch updates openvino-sys from lazy_static to once_cell.
[in wasmtime]: https://github.com/bytecodealliance/wasmtime/pull/4368
=> Migrate from lazy_static to once_cell.

crates/openvino-sys/src/linking/runtime.rs, crates/openvino/src/blob.rs, crates/openvino/src/core.rs, crates/openvino/src/error.rs, crates/openvino/src/lib.rs, crates/openvino/src/network.rs, crates/openvino/src/request.rs, crates/openvino/src/util.rs
A new version of Rust has introduced several new lints: this fixes the use of `$crate` in macros (an error) and uses `std::ptr::addr_of_mut!` in a variety of places (a warning).
=> Fix new clippy warnings

.github/workflows/main.yml
As noted in GitHub's [supported runners] documentation, GitHub is in the process of transitioning `ubuntu-latest` from `ubuntu-20.04` to `ubuntu-22.04` (jammy). Since OpenVINO does not yet have installation packages for Ubuntu 22.04, this change pins the GitHub runner to the older version for now.
[supported runners]: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
=> ci: pin GitHub runner to Ubuntu 20.04

crates/openvino/src/blob.rs
This depends on #54.
Current implementation of `Blob::tensor_desc()` always panics, because it doesn't trim dimensions array and passes the full `[u8; 8]` into `TensorDesc::new()`, which panics with `assertion failed: dimensions.len() < 8`.
This change fixes that by constructing `tensor_desc_t` directly, since we have all the members of it. I also changed accessor functions to use `MaybeUninit`, which is faster. There is no need to initialize all of them with default values.
=> Fix Blob::tensor_desc()

crates/openvino/src/blob.rs
As discussed [here], this change adds a (perhaps overkill) safety check of the size of the dimensions array returned by the OpenVINO library. The added assertion is trying to avoid the improbable case where some future version of the OpenVINO library returns a dimensions array with size different than the one auto-generated in the bindings; see `struct dimensions` in `openvino-sys/src/generated/types.rs`.
[here]: https://github.com/intel/openvino-rs/pull/56#discussion_r1041570646
=> Double-check size of returned blob dimensions

crates/openvino/src/blob.rs, crates/openvino/src/tensor_desc.rs
These likely are due to a new version of clippy somewhere.
=> lint: fix several new lint issues found

.github/workflows/main.yml, Cargo.lock, crates/openvino-finder/src/lib.rs, crates/openvino-sys/build.rs, crates/openvino/Cargo.toml, crates/openvino/src/core.rs, crates/openvino/src/error.rs
Now that OpenVINO 2022.3 is released, this updates the CI to use it during the build and test tasks.
=> ci: build against more versions

README.md, crates/openvino-finder/README.md, crates/openvino-finder/src/lib.rs, crates/xtask/src/bump.rs
`openvino-finder` encodes some rather complex logic to find OpenVINO files over several versions. This change describes that logic (and the rationale for it) in more detail and moves this text to the Rust documentation, closer to the code.
=> docs: describe how OpenVINO paths are found

crates/openvino-finder/src/lib.rs, crates/openvino/src/blob.rs, crates/openvino/src/core.rs, crates/openvino/src/lib.rs, crates/xtask/src/bump.rs, crates/xtask/src/publish.rs
This PR fixes some of the review comments suggested in #74 (I can't push to the original branch).
=> fix: clippy warnings

.github/workflows/main.yml
This change ostensibly protects the repository from CI attacks by limiting wha the `GITHUB_TOKEN` can do. See the token permissions documentation at:
- [OpenSSF]
- [GitHub]
[OpenSSF]: https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
[GitHub]: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
=> ci: prevent `GITHUB_TOKEN` from modifying the repository

crates/openvino-tensor-converter/Cargo.lock, crates/openvino-tensor-converter/Cargo.toml, crates/openvino-tensor-converter/src/lib.rs, crates/openvino-tensor-converter/src/main.rs, crates/openvino-tensor-converter/tests/conversion.rs
The `openvino-tensor-converter` crate is a helpful extension to this project but not crucial, thus it does not receive as much attention as other parts. It is useful for generating tensor files of various shapes from images (e.g., for test fixtures), so I haven't felt the need to remove it yet. Its dependencies had fallen far out of date and included a very old version of `shlex` that has security vulnerabilities. By updating to the latest `opencv` crate version, this dependency is also updated. This change also updates the converter code to fit the latest `opencv` API shape and `cargo-clippy` guidance.
=> chore: update OpenCV version in `openvino-tensor-converter`

crates/openvino/src/dimension.rs, crates/openvino/src/lib.rs, crates/openvino/src/model.rs, crates/openvino/src/node.rs, crates/openvino/src/partial_shape.rs, crates/openvino/src/rank.rs, crates/openvino/src/shape.rs
To be able to interrogate the shape of an arbitrary model's inputs and outputs at runtime, we need to wrap and expose the partial shape and related structs.
=> Expose model's partial shape and related types

crates/openvino/src/core.rs, crates/openvino/src/layout.rs, crates/openvino/src/model.rs, crates/openvino/src/partial_shape.rs, crates/openvino/src/prepostprocess.rs, crates/openvino/src/request.rs, crates/openvino/src/shape.rs, crates/openvino/src/tensor.rs, crates/openvino/src/util.rs
This is the result of running `cargo clippy` and resolving some of the warnings; it also refactors a few functions and improves some documentation, but does not change any logic.
=> Fix several clippy-related issues

crates/openvino/src/core.rs, crates/openvino/src/dimension.rs, crates/openvino/src/layout.rs, crates/openvino/src/model.rs, crates/openvino/src/node.rs, crates/openvino/src/partial_shape.rs, crates/openvino/src/prepostprocess.rs, crates/openvino/src/rank.rs, crates/openvino/src/request.rs, crates/openvino/src/shape.rs, crates/openvino/src/tensor.rs, crates/openvino/src/util.rs
See the commit messages for what this entails; this is a refactoring and should not involve any logic changes.
=> Rename `instance` field to `ptr`

crates/openvino/src/prepostprocess.rs, crates/openvino/tests/classify-alexnet.rs, crates/openvino/tests/classify-inception.rs, crates/openvino/tests/classify-mobilenet.rs
This change refactors the `prepostprocess` module by moving code around, renaming things, and eliminating some extra code. The one key change to look out for that is not trivial is the switch to use `&mut self` for functions that use `*mut ...` pointers. This makes use of Rust's builtin borrow checking to avoid concurrent mutable access to the OpenVINO internal objects, which is hidden away by our `unsafe` FFI calls.
=> Refactor the pre-processing pipeline

.github/workflows/main.yml
- Removed older openvino versions supported from CI 2023.1.0 and 2022.3.0
- Added newer openvino versions supported in CI 2024.1.0
- Added apt install and check for oldest (along with newest) supported versions i.e. 2023.2.0 and 2024.1.0 here
=> Update CI to remove old openvino versions

.github/workflows/main.yml, crates/openvino-finder/src/lib.rs, crates/openvino-sys/build.rs, crates/openvino-sys/src/lib.rs
- Fix finding of OpenVINO 2024.0.0 on Windows
- Fix linking Windows
=> Fix windows linking

crates/openvino/src/core.rs, crates/openvino/src/device_type.rs, crates/openvino/src/lib.rs, crates/openvino/tests/classify-alexnet.rs, crates/openvino/tests/classify-inception.rs, crates/openvino/tests/classify-mobilenet.rs
=> Add device type

.github/workflows/main.yml, crates/openvino/src/core.rs, crates/openvino/src/request.rs
We've run into an issue with `Core::read_model_from_buffer` -- the wrapper assumes that the in-memory model is a valid string. However, non-native models, such as ONNX, aren't valid strings. Attempting to load an ONNX model results in an error creating a CString due to non-terminating null characters.
We propose to change the method interface to support arbitrary byte models rather than just strings.
Furthermore, we propose to make the weight tensor an optional argument, as it doesn't apply to non-native models.
=> Support loading non-string models from memory

crates/openvino/src/lib.rs, crates/openvino/src/property.rs, crates/openvino/src/version.rs
- Add property enum
- Add version module
=> add property and version modules

crates/openvino/src/request.rs
Add a few remaining infer_request functions
=> add infer_request functions

Cargo.lock, crates/openvino-sys/src/generated/functions.rs, crates/xtask/Cargo.toml, crates/xtask/src/codegen.rs
- Replaces variadic args `...` with `property_key: *const ::std::os::raw::c_char, property_value: *const ::std::os::raw::c_char` for 2 functions, `ov_compiled_model_set_property` and `ov_core_set_property`
- This is needed because variadic args do not yet work with runtime linking (link macro in `runtime.rs`)
- Other functions like `ov_core_compile_model` also have `...`, but these are not replaced as above since. The only place where they are replaced are functions which expect 1 or more pairs of property_key/property_value, but not in functions which expect 0 or more.
- The optional properties passed in `ov_core_compile_model` set properties just for that compiled model, while properties set in `ov_core_set_property` are for all models compiled with that core. Similarly, some subtle …
=> Replace variadic arguments with fixed

crates/openvino/src/core.rs, crates/openvino/src/dimension.rs, crates/openvino/src/layout.rs, crates/openvino/src/model.rs, crates/openvino/src/node.rs, crates/openvino/src/partial_shape.rs, crates/openvino/src/prepostprocess.rs, crates/openvino/src/rank.rs, crates/openvino/src/request.rs, crates/openvino/src/shape.rs, crates/openvino/src/tensor.rs, crates/openvino/tests/classify-alexnet.rs, crates/openvino/tests/classify-inception.rs, crates/openvino/tests/classify-mobilenet.rs
- Added `as_mut_ptr()` and `as_ptr()` where required to return
- Added `#[inline]` compiler hints
=> Add `as_mut_ptr` and inline hints

Cargo.toml, crates/openvino-finder/Cargo.toml, crates/openvino-sys/Cargo.toml, crates/openvino/Cargo.toml, crates/xtask/src/bump.rs, crates/xtask/src/publish.rs, crates/xtask/src/util.rs
This change only should update the location of the version string to a central place: the top-level `Cargo.toml`. This causes some churn in the `xtask` commands but the overall result should be the same.
=> Switch to using a centrally-located workspace version

crates/openvino/src/core.rs, crates/openvino/src/layout.rs, crates/openvino/src/model.rs, crates/openvino/src/prepostprocess.rs, crates/openvino/src/request.rs, crates/openvino/src/util.rs
The `cstr` macro uses `CString::into_raw()` to get the c-compatible string pointer.
However, per [Rust doc](https://doc.rust-lang.org/std/ffi/struct.CString.html#method.into_raw), `into_raw` actually leaks the pointer if it isn't reclaimed and deallocated using `from_raw`.
This PR changes the macro and its usage to:
1. Create a CString
2. Keep it alive as we take its pointer (`as_ptr`)
3. Pass its `as_ptr` to the c functions
=> Fix cstr macro leak

crates/openvino/src/core.rs, crates/openvino/src/property.rs
- Resolves https://github.com/intel/openvino-rs/issues/122
- Removed functions which allowed get/set properties without device name. This use case is not documented in openvino docs, and the openvino c-api do not allow not passing device name, so this change adheres to that.
- Pass `property_key` as reference instead of value
- Added tests related to supported properties and RW properties for CPU
- I've opened an issue here https://github.com/openvinotoolkit/openvino/issues/24911 and will update with more tests based on the resolution there at a later point if need be (for example adding more tests checking unsupported cpu properties etc. It is undocumented right now, so haven't added those tests yet).
=> Fix core get/set properties

crates/openvino/src/prepostprocess.rs, crates/openvino/src/tensor.rs, crates/openvino/tests/classify-alexnet.rs, crates/openvino/tests/classify-inception.rs, crates/openvino/tests/classify-mobilenet.rs
- Remove `new_from_host_ptr` function, since it was easy `data` field to go out of scope, causing a seg fault later in openvino.
- Now using `copy_from_buffer_slice` on the buffer of a newly created tensor
=> remove tensor new_from_host_ptr function

crates/openvino/src/prepostprocess.rs, crates/openvino/src/tensor.rs, crates/openvino/tests/classify-alexnet.rs, crates/openvino/tests/classify-inception.rs, crates/openvino/tests/classify-mobilenet.rs
This refactors the data accessor functions in `Tensor` to be more consistent with conventions elsewhere (e.g., `get_`). It also checks a bit more robustly whether the underlying pointer can in fact be casted to the type we expect.
=> Replace `Tensor::buffer_mut`

crates/openvino/tests/memory-safety.rs
This test originates from some strange segfaults that we observed while using the OpenVINO C library. Because OpenVINO is taking a pointer to a tensor when constructing a model, we want to be sure that we do the right thing on this side of the FFI boundary.
=> Add a memory safety test

RELEASING.md
This should help document the steps we usually take with new versions of these crates.
=> Add release guide

crates/openvino/src/tensor.rs
When checking that tensor data can be converted to a slice of `T`, we previously were checking the right things: is the length right? Is the alignment correct? Turns out there is a `std` function that does this for us: `slice::align_to`. Replacing the custom check with the `std` version should have no effect on the code other than clarity.
=> Use `slice::align_to`

crates/openvino/src/core.rs, crates/openvino/src/tensor.rs, crates/openvino/src/util.rs
This should make it more obvious how to construct and then fill a tensor from in-memory data. Still unresolved: it would be nice to have all the lifetimes wired up so that we can avoid a copy over to the C++ side, but that is left open for now.
=> doc: add an in-memory tensor data example

.github/workflows/scan.yml
This will integrate `clippy` with GitHub's code scanning feature.
=> ci: add initial code scan configuration

crates/xtask/src/main.rs, crates/xtask/src/update.rs, crates/xtask/src/util.rs
Every so often the upstream OpenVINO repository releases a new version. This new task, `cargo xtask update <tag>`, will run some Git commands to update Git submodule tracked by this repository. Since each release may slightly tweak the header files, this new task is expected to be used immediately prior to `cargo xtask codegen; cargo test`.
=> Add `xtask` to update upstream submodule

crates/openvino/src/core.rs, crates/openvino/src/device_type.rs, crates/openvino/src/dimension.rs, crates/openvino/src/element_type.rs, crates/openvino/src/error.rs, crates/openvino/src/layout.rs, crates/openvino/src/lib.rs, crates/openvino/src/model.rs, crates/openvino/src/node.rs, crates/openvino/src/partial_shape.rs, crates/openvino/src/prepostprocess.rs, crates/openvino/src/property.rs, crates/openvino/src/rank.rs, crates/openvino/src/request.rs, crates/openvino/src/shape.rs, crates/openvino/src/tensor.rs, crates/openvino/src/util.rs, crates/openvino/src/version.rs
This fixes up a few issues I noticed; see commits for more details.
=> doc: update prior to release

.github/workflows/main.yml, crates/openvino-sys/src/lib.rs, crates/openvino/tests/memory-safety.rs, crates/openvino/tests/setup.rs, crates/openvino/tests/util.rs
In #143, we discovered that upstream OpenVINO had changed the `ov_element_type_e` enum in a backwards-incompatible way. This means that a mismatch between the Rust bindings (based on the C headers) and the shared library will result in tensors being created with the wrong type (e.g., `U64` instead of `U8`). To avoid this situation, this change reads the OpenVINO library version at runtime (e.g., every time a `Core` is created) and fails with an error if the version is older than 2024.2, when the breaking change was introduced.
The effect of merging this change is that newer bindings will fail when used with older libraries, which could be problematic for users. Users could always use an older version of the library (e.g., `v0.7.*`) instead. And the alternative, letting users create …
=> Check version; fail if pre-2024.2

Cargo.lock, crates/openvino-sys/Cargo.toml, crates/openvino/src/device_type.rs, crates/xtask/Cargo.toml, deny.toml
This PR used `cargo upgrade` from the `cargo-edit` crate to upgrade several dependencies in this project. One notable absence is `bindgen`, which `cargo upgrade` says it could not upgrade in a compatible way (this is probably the right thing for now since it would require tweaks to the generated files).
This upgrade moves the version of `anstream` to 0.6.18 which resolves the unsoundness reported in [RUSTSEC-2024-0404]. `anstream` is used by the `xtask` crate (not public; only for local developer tooling) and as a test dependency of `openvino-sys`, so the unsoundness does not affect the published library crates.
[RUSTSEC-2024-0404]: https://rustsec.org/advisories/RUSTSEC-2024-0404
=> Upgrade several dependencies

.github/workflows/main.yml, crates/openvino-sys/src/lib.rs
This enables `clippy::suspicious_doc_comments` that is a bit too strict for the generated code.
=> Allow a pedantic doc comment lint

.github/workflows/scan.yml
This CI check fails if `cargo clippy` fails, which is unfortunate since we really want the output of `cargo clippy`, errors and all, available to the CodeQL action. This change attempts to remedy that by ignoring any error code returned by `cargo clippy` (and only `cargo clippy`; we expect the other steps to succeed.
=> Make code scan more robust

.github/workflows/main.yml
The purpose of this is to more quickly identify CI bit rot (e.g., outdated packages, runner images).  Any failures should result in notifications, prompting quicker resolution.
Also, this includes a manual trigger for starting CI runs from https://github.com/intel/openvino-rs/actions/workflows/main.yml.
=> ci: automatically run every two weeks

crates/openvino-sys/src/linking/runtime.rs
This was pointed out by code scan [#87]: clippy now says that "extern declarations without an explicit ABI are deprecated." This change adds the `"C"` ABI definition, matching the `extern "C"` we use above when we declare each function.
[#87]: https://github.com/intel/openvino-rs/security/code-scanning/87
=> Specify the ABI of each linked-to OpenVINO function

Cargo.lock, Cargo.toml, crates/openvino-sys/Cargo.toml, crates/openvino-sys/src/linking/runtime.rs, crates/openvino/Cargo.toml
As pointed out by code scan [#88], `std::sync::LazyLock` is the standard way to initialize static values. `LazyLock` has been available since Rust [v1.80.0]. This change switches to `LazyLock` and removes the now-unnecessary `once_cell` crate. It also throws a few `rust-version` annotations in to remind users what version of Rust to use.
[#88]: https://github.com/intel/openvino-rs/security/code-scanning/88
[v1.80.0]: https://releases.rs/docs/1.80.0
=> Replace `once_cell` with the now-standard `LazyLock`

.github/workflows/main.yml, crates/openvino-sys/src/generated/functions.rs, crates/openvino-sys/src/generated/types.rs, crates/openvino/src/core.rs, crates/openvino/src/element_type.rs, crates/openvino/src/property.rs
This takes some of the work by @Rickvanderveen in #159 (thanks!) and makes the crate compatible with OpenVINO v2025.1.0 and above. I've documented the breaking ABI change from upstream in https://github.com/intel/openvino-rs/issues/167 and will follow this up with a fix to only allow this code to work with versions 2025.1.0 and above.
=> Upgrade bindings to v2025.1.0

crates/openvino-sys/src/lib.rs
Much like #149, this adds a dynamic check to avoid pre-2025.1 versions when dynamically linking an OpenVINO library. The reasons for this are documented in [#167].
[#167]: https://github.com/intel/openvino-rs/issues/167
=> Fail if dynamically loading a pre-2025.1 OpenVINO library

crates/openvino-tensor-converter/src/lib.rs, crates/openvino-tensor-converter/src/main.rs, crates/openvino-tensor-converter/tests/conversion.rs
This adds to the openvino-tensor-converter crate the option to convert an image to NCHW format if needed.
Example usage -
```
cargo run -p openvino-tensor-converter -- $TMP_DIR/val2017/000000062808.jpg $FIXTURE_DIR/tensor-1x224x224x3-f32.bgr 224x224x3xfp32 nchw
```
Used this to generate asset to solve this issue https://github.com/bytecodealliance/wasmtime/issues/10867
@abrown
=> Add nchw conversion option

.github/workflows/main.yml, crates/openvino-sys/src/generated/functions.rs
This is the result of running:
```
cargo xtask update 2025.2.0
cargo xtask codegen
```
This also updates CI to use v2025.2.0 during testing.
=> Upgrade bindings to v2025.2.0
